server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway

  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
      - id: users
        uri: lb://USER-SERVICE
        predicates:
          - Path=/api/v1/user/**
      - id: order
        uri: lb://ORDER-SERVICE
        predicates:
          - Path=/api/v1/orders/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://143.198.63.47:9090/auth/realms/alpha-trade


  main:
    allow-bean-definition-overriding: true