server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


spring:
  application:
    name: api-gateway

  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
      - id: users
        uri: lb://USER-SERVICE
        predicates:
          - Path=/api/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/auth/realms/micro-trading-system


  main:
    allow-bean-definition-overriding: true